export const portfoliodata = [
    {
        id: 1,
        src: '/home/displayportfolio/title/portfolio_title_slide_personal.png',
        alt: '개인프로젝트제목슬라이드',
        noClick: true,
    },
    {
        id: 2,
        title: 'PRETCOORD',
        titledetail: '패션 3D 플랫폼 사이트\n랜딩 페이지 코드 리메이크',
        src: '/home/displayportfolio/thumb/pretcoord.png',
        alt: '개인포폴241216',
        thumbstartdate: '2024.12',
        period_start: '2024.12.16',
        period_end: '2025.01.06',
        desc: "'Pretcoord'사이트를 최신 프레임워크인 NEXT.js를 활용해 리메이크한 프로젝트 입니다. UI만 기존 사이트를 참고하여 GSAP 과 react 훅을 이용해 개발하였습니다.",
        deploy: 'https://pretcoordremake.netlify.app',
        code: 'https://github.com/peaceRyun/pretcroodclone',
        techStack: ['React', 'Next.js', 'Tailwind CSS', 'SASS', 'JS', 'GSAP', 'Swiper'],
        Requests: '',
        keyFeatures: [
            {
                title: '스크롤 인터렉션 효과',
                img: '',
                desc1: '인트로 영상을 scale 값을 조절하여 스크롤을 통해 더 확대될 수 있도록 설계하여 몰입감을 높였습니다. ',
                desc2: '사용자가 Pretcoord 소개 문구를 재미나게 읽을 수 있도록 스크롤 할때마다 글씨가 빛나게끔 구현하였습니다.',
            },
            {
                title: '반응형',
                img: '',
                desc1: '모바일, 태블릿, 모니터 등 어떤 디바이스에서도 일관된 사용자 경험을 제공합니다.',
            },
            {
                title: '부드러운 애니메이션',
                img: '',
                desc1: '링크 글씨 hover효과(Glow, line Effect)',
            },
        ],
        troubleShooting: [
            {
                title: '애니메이션 구현',
                problem:
                    'GSAP을 react로 써보는 첫 프로젝트 였기에 처음 intro에 해당하는 video섹션의 마크업과 애니메이션부터 적용하는 것조차 쉽지 않았습니다. ',
                solution:
                    'react에서 쓸 수 있는 hook 중에 하나인 useRef에 대한 개념 이해,  timeline 적용법, props 전달을 공부하며 설계를 해보았습니다. 끝에 가서는 Gsap  animation 관련 코드를 한 파일에 넣어 불러오는 방식으로 관리하여 커스텀 훅으로 빼서 코드의 가독성을 높일 수 있었습니다.',
            },
        ],
    },
    {
        id: 3,
        title: 'Sunfish',
        titledetail: '스트레스 관리 모바일웹',
        src: '/home/displayportfolio/thumb/sunfish.png',
        alt: '개인포폴241123',
        thumbstartdate: '2024.11',
        period_start: '2024.11.23',
        period_end: '2024.12.14',
        desc: '자체적으로 기획해서 만들어본 스트레스 관리 모바일 웹 입니다. 간편한 ToDo 전광판 등록 기능, 요리API를 끌어온 비스트레스 음식 간편 검색, 감정 일기장으로 구성되어 있습니다. 최신 프레임워크 Next.js를 활용하여 개발했습니다.',
        deploy: 'https://sunfish2.vercel.app',
        code: 'https://github.com/peaceRyun/sunfish2',
        figma: 'https://www.figma.com/design/mseacF6eDnRzpwa9Uvzgr6/project2-sunfish?node-id=0-1&t=lQEK8zzdAbWtsgVh-1',
    },
    {
        id: 4,
        title: '삼천리 자전거 ',
        titledetail: '자전거 브랜드/쇼핑몰 페이지\n리뉴얼',
        src: '/home/displayportfolio/thumb/samcheonbike.png',
        alt: '개인포폴241014',
        thumbstartdate: '2024.10',
        period_start: '2024.10.14',
        period_end: '2024.11.20',
        desc: '기존 삼천리자전거 웹사이트를 GSAP 스크롤트리거 애니메이션과 반응형 웹 등의 최신 웹사이트 트렌드 방법으로 리메이크한 HTML/SCSS/JS 프로젝트입니다.  ',
        deploy: 'peaceryun.github.io/SCLBike/pages',
        code: 'https://github.com/peaceRyun/SCLBike',
        figma: 'https://www.figma.com/design/UFpbjWERXFC5aZUoy9A2zf/project1_3000bike-remake-with-html%2Fcss%2Fjs%2Bgsap?node-id=2001-31042&t=l8a6z3s12dIYSfsw-1',
    },
    {
        id: 5,
        src: '/home/displayportfolio/title/portfolio_title_slide_team.png',
        alt: '팀프로젝트제목슬라이드',
        noClick: true,
    },
    {
        id: 6,
        title: 'VanCleef',
        titledetail: '홈페이지\n리뉴얼',
        src: '/home/displayportfolio/thumb/vancleef.png',
        alt: '팀포폴250226',
        thumbstartdate: '2025.02',
        period_start: '2025.02.26',
        period_end: '2025.03.24',
        desc: '기존 반클리프 아펠 사이트를 기능까지 리메이크 해본 React Vite 웹 개발 협업 프로젝트 입니다. 불편한 UX와 동적 인터렉티브 요소의 부족을 개선해 보았습니다. 로컬스토리지를 활용해보기 위해 목업 데이터 구조 설계부터 시작하여 장바구니, 상품별 리뷰&문의, 로그인&회원가입, 회원정보 불러오기&수정 등을 구현 하였습니다. ',
        deploy: 'project-vancleef.vercel.app',
        code: 'https://github.com/peaceRyun/project-vancleef',
        figma: 'https://www.figma.com/design/mmwiSjjdtvvVi1dB5dsiZt/D2C-Project?node-id=1-88&t=IsmeicsJpaB2Dogg-1',
    },
    {
        id: 7,
        title: 'VIBO',
        titledetail: 'OTT 자체기획 홈페이지',
        src: '/home/displayportfolio/thumb/vibo.png',
        alt: '팀포폴241231',
        thumbstartdate: '2024.12',
        period_start: '2024.12.31',
        period_end: '2025.02.25',
        desc: '상업성 높은 3개의 사이트(넷플릭스, 왓챠, 티빙)을 재해석하여 탄생한 OTT 사이트 “ViBo”입니다.  React Vite를 활용해 콘텐츠별 리뷰 기능 및 UI 개선, 동적 애니메이션을 통한 홍보 강화를 통해 기존 사이트들의 부족한 사용자 경험을 보완하여 만든 순수 React 사이트 입니다. 4명의 협업을 통해 만들어졌습니다.',
        deploy: 'viboott.vercel.app/',
        code: 'https://github.com/peaceRyun/vibo',
        figma: 'https://www.figma.com/design/2RnUhIuvGnwXrh5v91NX04/OTT-작업지침서?node-id=0-1&t=Vk9L49iYm3Ad85gQ-1',
    },
];
