import './globals.css';
import { Poppins } from 'next/font/google';
import localFont from 'next/font/local';
import ClientLayout from './csrcomponents/ClientLayout';
import CustomCursor from './ui/cursor/Cursor';
import Header from './layouts/header/Header';
import Footer from './layouts/footer/Footer';

export const metadata = {
    title: 'FrontEnd Dev KYG',
    description: 'Generated by create next app',
};

const pretendard = localFont({
    src: '/fonts/pretendardVariable.woff2',
    display: 'swap',
    preload: true,
    weight: '400 700',
});

const clashv = localFont({
    src: '/fonts/ClashDisplay-Variable.woff2',
    display: 'swap',
    preload: true,
});

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({ children }) {
    return (
        <html
            lang='ko'
            className={`${poppins.className} ${pretendard.className} ${clashv.className}`}
            suppressHydrationWarning
        >
            <head>
                <meta name='viewport' content='width=device-width, initial-scale=1.0' />
            </head>
            <body>
                <ClientLayout>
                    <CustomCursor />
                    <Header />
                    {children}
                    <Footer />
                </ClientLayout>
            </body>
        </html>
    );
}
